In [2]:
import numpy as np
import pandas as pd

In [3]:
#1.- Obtener información del archivo trade_details:
read_trade_details = pd.read_csv('trade_details.csv', sep=';') # indico el separador porque viene con ; y entonces no es del todo legible, lo cambio a , para que se muestr bien columnas y valores
read_trade_details

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
0,IRD,BOND,NaN,316391872,678876251,2021-09-22
1,CURR,FXD,FXD,32734782,54853428,2021-09-22
2,IRD,LN_BR,NaN,1111,2222,2022-10-06
3,IRD,IRS,NaN,2222222,2222222,2024-10-15
4,SCF,SCF,SCF,3815982,3672136,NaN
5,IRD,LN_BR,NaN,14596583,13774383,2020-12-29
6,IRD,IRS,NaN,18343978,17356077,2024-10-15
7,IRD,LN_BR,NaN,19203839,18176215,2022-10-06
8,IRD,CF,NaN,20513130,19433281,2021-07-06
9,IRD,CF,NaN,20533916,19453781,2023-07-06
10,IRD,IRS,NaN,21183317,20077630,2040-07-13
11,IRD,IRS,NaN,33333333,33333333,2024-10-15
12,IRD,IRS,NaN,111222333,111222333,2024-10-15
13,IRD,IRS,NaN,222333111,222333111,2020-12-30
14,IRD,IRS,NaN,333111222,333111222,2020-12-12
15,IRD,IRS,NaN,444111222,444111222,NaN
16,IRD,IRS,NaN,555111222,555111222,NaN
17,IRD,IRS,NaN,564367838,564367838,2024-10-15
18,IRD,IRS,NaN,556111214,556111214,NaN
19,EQD,EQUIT,FWD,10000001,10000001,2019-07-02
20,IRD,BOND,FWD,10000009,10000009,2021-06-12
21,CURR,FXD,SWLEG,19665185,18622136,2020-04-29
22,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
23,CURR,FXD,SWLEG,19772399,18724280,NaN
24,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
25,CURR,FXD,SWLEG,20980932,19883451,NaN
26,CURR,FXD,SWLEG,20980933,19883451,NaN
27,CURR,FXD,SWLEG,22798004,21622649,NaN
28,CURR,FXD,SWLEG,22798005,21622649,NaN
29,CURR,FXD,SWLEG,20665177,19622128,2020-04-29
30,CURR,FXD,SWLEG,20665178,19622128,2020-12-30

In [4]:
#2.- Obtener información del archivo trade_details_snapshot:
read_trade_details_snapshot = pd.read_csv('trade_details_snapshot.csv', sep=';')
read_trade_details_snapshot

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
0,CURR,FXD,SWLEG,19665185,18622136,2020-04-29
1,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
2,CURR,FXD,SWLEG,19772399,18724280,2020-11-05
3,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
4,CURR,FXD,SWLEG,20980932,19883451,2020-02-02
5,CURR,FXD,SWLEG,20980933,19883451,2020-01-19
6,CURR,FXD,SWLEG,22798004,21622649,2021-05-04
7,CURR,FXD,SWLEG,22798005,21622649,2021-05-11
8,CURR,FXD,SWLEG,20665177,19622128,2020-04-29
9,CURR,FXD,SWLEG,20665178,19622128,2020-12-30
10,IRD,BOND,NaN,316391872,678876251,2021-09-22
11,CURR,FXD,FXD,32734782,54853428,2021-09-22
12,IRD,LN_BR,NaN,1111,2222,2022-10-06
13,IRD,IRS,NaN,2222222,2222222,2024-10-15
14,SCF,SCF,SCF,3815982,3672136,2021-05-04
15,IRD,LN_BR,NaN,14596583,13774383,2020-12-29
16,IRD,IRS,NaN,18343978,17356077,2024-10-15
17,IRD,LN_BR,NaN,19203839,18176215,2022-10-06
18,IRD,CF,NaN,20513130,19433281,2021-07-06
19,IRD,CF,NaN,20533916,19453781,2023-07-06
20,IRD,IRS,NaN,21183317,20077630,2040-07-13
21,IRD,IRS,NaN,33333333,33333333,2024-10-15
22,IRD,IRS,NaN,111222333,111222333,2024-10-15
23,IRD,IRS,NaN,222333111,222333111,2020-12-30
24,IRD,IRS,NaN,333111222,333111222,2020-12-12
25,IRD,IRS,NaN,444111222,444111222,2021-05-04
26,IRD,IRS,NaN,555111222,555111222,2021-05-04
27,IRD,IRS,NaN,564367838,564367838,2024-10-15
28,IRD,IRS,NaN,556111214,556111214,2021-05-04
29,EQD,EQUIT,FWD,10000001,10000001,2019-07-02
30,IRD,BOND,FWD,10000009,10000009,2021-06-12
31,IRD,IRS,NaN,333244333,333244333,2024-10-15
32,IRD,IRS,NaN,35662435,35662435,2024-10-15
33,IRD,IRS,NaN,3323455,3323455,2020-12-30
34,IRD,IRS,NaN,67746567,67746567,2020-12-12
35,IRD,IRS,NaN,84564656,84564656,2021-05-04

In [175]:
#3.- Ordenar ambos archivos la columna de maturity de forma descendente para saber cual es el dato más actual
#*long leg*, es decir, la que tiene una mayor fecha de vencimiento (fecha más actual de la columna maturity).
print(read_trade_details.sort_values('maturity', ascending=False))
read_trade_details_snapshot.sort_values('maturity', ascending=False)

   mfamily mgroup  mtype  origin_trade_number  origin_contract_number  \
10     IRD    IRS    NaN             21183317                20077630
12     IRD    IRS    NaN            111222333               111222333
3      IRD    IRS    NaN              2222222                 2222222
6      IRD    IRS    NaN             18343978                17356077
17     IRD    IRS    NaN            564367838               564367838
11     IRD    IRS    NaN             33333333                33333333
9      IRD     CF    NaN             20533916                19453781
2      IRD  LN_BR    NaN                 1111                    2222
7      IRD  LN_BR    NaN             19203839                18176215
24    CURR    FXD  SWLEG             19772400                18724280
1     CURR    FXD    FXD             32734782                54853428
0      IRD   BOND    NaN            316391872               678876251
8      IRD     CF    NaN             20513130                19433281
20     IRD   BOND    FWD             10000009                10000009
13     IRD    IRS    NaN            222333111               222333111
22    CURR    FXD  SWLEG             19665186                18622136
30    CURR    FXD  SWLEG             20665178                19622128
5      IRD  LN_BR    NaN             14596583                13774383
14     IRD    IRS    NaN            333111222               333111222
21    CURR    FXD  SWLEG             19665185                18622136
29    CURR    FXD  SWLEG             20665177                19622128
19     EQD  EQUIT    FWD             10000001                10000001
4      SCF    SCF    SCF              3815982                 3672136
15     IRD    IRS    NaN            444111222               444111222
16     IRD    IRS    NaN            555111222               555111222
18     IRD    IRS    NaN            556111214               556111214
23    CURR    FXD  SWLEG             19772399                18724280
25    CURR    FXD  SWLEG             20980932                19883451
26    CURR    FXD  SWLEG             20980933                19883451
27    CURR    FXD  SWLEG             22798004                21622649
28    CURR    FXD  SWLEG             22798005                21622649

      maturity
10  2040-07-13
12  2024-10-15
3   2024-10-15
6   2024-10-15
17  2024-10-15
11  2024-10-15
9   2023-07-06
2   2022-10-06
7   2022-10-06
24  2021-11-05
1   2021-09-22
0   2021-09-22
8   2021-07-06
20  2021-06-12
13  2020-12-30
22  2020-12-30
30  2020-12-30
5   2020-12-29
14  2020-12-12
21  2020-04-29
29  2020-04-29
19  2019-07-02
4          NaN
15         NaN
16         NaN
18         NaN
23         NaN
25         NaN
26         NaN
27         NaN
28         NaN

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
20,IRD,IRS,NaN,21183317,20077630,2040-07-13
32,IRD,IRS,NaN,35662435,35662435,2024-10-15
31,IRD,IRS,NaN,333244333,333244333,2024-10-15
21,IRD,IRS,NaN,33333333,33333333,2024-10-15
16,IRD,IRS,NaN,18343978,17356077,2024-10-15
27,IRD,IRS,NaN,564367838,564367838,2024-10-15
22,IRD,IRS,NaN,111222333,111222333,2024-10-15
13,IRD,IRS,NaN,2222222,2222222,2024-10-15
19,IRD,CF,NaN,20533916,19453781,2023-07-06
12,IRD,LN_BR,NaN,1111,2222,2022-10-06
17,IRD,LN_BR,NaN,19203839,18176215,2022-10-06
3,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
10,IRD,BOND,NaN,316391872,678876251,2021-09-22
11,CURR,FXD,FXD,32734782,54853428,2021-09-22
18,IRD,CF,NaN,20513130,19433281,2021-07-06
30,IRD,BOND,FWD,10000009,10000009,2021-06-12
7,CURR,FXD,SWLEG,22798005,21622649,2021-05-11
25,IRD,IRS,NaN,444111222,444111222,2021-05-04
26,IRD,IRS,NaN,555111222,555111222,2021-05-04
28,IRD,IRS,NaN,556111214,556111214,2021-05-04
35,IRD,IRS,NaN,84564656,84564656,2021-05-04
14,SCF,SCF,SCF,3815982,3672136,2021-05-04
6,CURR,FXD,SWLEG,22798004,21622649,2021-05-04
1,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
23,IRD,IRS,NaN,222333111,222333111,2020-12-30
9,CURR,FXD,SWLEG,20665178,19622128,2020-12-30
33,IRD,IRS,NaN,3323455,3323455,2020-12-30
15,IRD,LN_BR,NaN,14596583,13774383,2020-12-29
24,IRD,IRS,NaN,333111222,333111222,2020-12-12
34,IRD,IRS,NaN,67746567,67746567,2020-12-12
2,CURR,FXD,SWLEG,19772399,18724280,2020-11-05
8,CURR,FXD,SWLEG,20665177,19622128,2020-04-29
0,CURR,FXD,SWLEG,19665185,18622136,2020-04-29
4,CURR,FXD,SWLEG,20980932,19883451,2020-02-02
5,CURR,FXD,SWLEG,20980933,19883451,2020-01-19
29,EQD,EQUIT,FWD,10000001,10000001,2019-07-02

In [6]:
#4.- Unir ambos Dataframe creando un DF donde se registraran todos los datos finales

#El método combina dos DataFrame y utiliza un valor del DataFrame si el primero tiene un valor NULL 
trade_fusion = pd.DataFrame(read_trade_details.combine_first(read_trade_details_snapshot))
trade_fusion

#--------------------ESTE METODO LO UTILIZE INICIALMENTE PARA HACER EL MERGE DE AMBOS DATAFRAME--------------
# trade_combi = pd.merge(read_trade_details,read_trade_details_snapshot, how='outer').sort_values('maturity')
# trade_combi

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
0,IRD,BOND,SWLEG,316391872,678876251,2021-09-22
1,CURR,FXD,FXD,32734782,54853428,2021-09-22
2,IRD,LN_BR,SWLEG,1111,2222,2022-10-06
3,IRD,IRS,SWLEG,2222222,2222222,2024-10-15
4,SCF,SCF,SCF,3815982,3672136,2020-02-02
5,IRD,LN_BR,SWLEG,14596583,13774383,2020-12-29
6,IRD,IRS,SWLEG,18343978,17356077,2024-10-15
7,IRD,LN_BR,SWLEG,19203839,18176215,2022-10-06
8,IRD,CF,SWLEG,20513130,19433281,2021-07-06
9,IRD,CF,SWLEG,20533916,19453781,2023-07-06
10,IRD,IRS,NaN,21183317,20077630,2040-07-13
11,IRD,IRS,FXD,33333333,33333333,2024-10-15
12,IRD,IRS,NaN,111222333,111222333,2024-10-15
13,IRD,IRS,NaN,222333111,222333111,2020-12-30
14,IRD,IRS,SCF,333111222,333111222,2020-12-12
15,IRD,IRS,NaN,444111222,444111222,2020-12-29
16,IRD,IRS,NaN,555111222,555111222,2024-10-15
17,IRD,IRS,NaN,564367838,564367838,2024-10-15
18,IRD,IRS,NaN,556111214,556111214,2021-07-06
19,EQD,EQUIT,FWD,10000001,10000001,2019-07-02
20,IRD,BOND,FWD,10000009,10000009,2021-06-12
21,CURR,FXD,SWLEG,19665185,18622136,2020-04-29
22,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
23,CURR,FXD,SWLEG,19772399,18724280,2020-12-30
24,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
25,CURR,FXD,SWLEG,20980932,19883451,2021-05-04
26,CURR,FXD,SWLEG,20980933,19883451,2021-05-04
27,CURR,FXD,SWLEG,22798004,21622649,2024-10-15
28,CURR,FXD,SWLEG,22798005,21622649,2021-05-04
29,CURR,FXD,SWLEG,20665177,19622128,2020-04-29
30,CURR,FXD,SWLEG,20665178,19622128,2020-12-30
31,IRD,IRS,NaN,333244333,333244333,2024-10-15
32,IRD,IRS,NaN,35662435,35662435,2024-10-15
33,IRD,IRS,NaN,3323455,3323455,2020-12-30
34,IRD,IRS,NaN,67746567,67746567,2020-12-12
35,IRD,IRS,NaN,84564656,84564656,2021-05-04

In [7]:
#5.- Filtro snapshot por la columna de mFamily = CURR para comprobar de los FXSwaps cuales estan con distinto trade_number y un mismo contract_number para obtener solo la *long leg*

filter_dfFusuion = trade_fusion.loc[:,'mfamily'] == 'CURR'
filter_FXSwaps = trade_fusion.loc[filter_dfFusuion]
filter_FXSwaps

# ----_ESTE FILTRO ERA UTILIZADO CON DATAFRAME DE LA COPIA DE SEGURIDAD_---
# filtro = read_trade_details_snapshot.loc[:,'mfamily'] == 'CURR'
# filtro_oden = read_trade_details_snapshot.loc[filtro]
# filtro_oden

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
1,CURR,FXD,FXD,32734782,54853428,2021-09-22
21,CURR,FXD,SWLEG,19665185,18622136,2020-04-29
22,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
23,CURR,FXD,SWLEG,19772399,18724280,2020-12-30
24,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
25,CURR,FXD,SWLEG,20980932,19883451,2021-05-04
26,CURR,FXD,SWLEG,20980933,19883451,2021-05-04
27,CURR,FXD,SWLEG,22798004,21622649,2024-10-15
28,CURR,FXD,SWLEG,22798005,21622649,2021-05-04
29,CURR,FXD,SWLEG,20665177,19622128,2020-04-29
30,CURR,FXD,SWLEG,20665178,19622128,2020-12-30

In [8]:
#6.-Eliminar del DataFrame Fusionado las filas que contengan la data short y asi solo dejar reflejadas las long leg

deleteFXSwaps_1 = trade_fusion[ (trade_fusion['origin_contract_number'] == 18622136) & (trade_fusion['maturity']== '2020-04-29')].index
deleteFXSwaps_2 = trade_fusion[ (trade_fusion['origin_contract_number'] == 18724280) & (trade_fusion['maturity']== '2020-11-05')].index
deleteFXSwaps_3 = trade_fusion[ (trade_fusion['origin_contract_number'] == 19883451) & (trade_fusion['maturity']== '2020-01-19')].index
deleteFXSwaps_4 = trade_fusion[ (trade_fusion['origin_contract_number'] == 21622649) & (trade_fusion['maturity']== '2021-05-04')].index
deleteFXSwaps_5 = trade_fusion[ (trade_fusion['origin_contract_number'] == 19622128) & (trade_fusion['maturity']== '2020-04-29')].index

trade_fusion.drop(deleteFXSwaps_1, inplace=True)
trade_fusion.drop(deleteFXSwaps_2, inplace=True)
trade_fusion.drop(deleteFXSwaps_3, inplace=True)
trade_fusion.drop(deleteFXSwaps_4, inplace=True)
trade_fusion.drop(deleteFXSwaps_5, inplace=True)

trade_fusion

,mfamily,mgroup,mtype,origin_trade_number,origin_contract_number,maturity
0,IRD,BOND,SWLEG,316391872,678876251,2021-09-22
1,CURR,FXD,FXD,32734782,54853428,2021-09-22
2,IRD,LN_BR,SWLEG,1111,2222,2022-10-06
3,IRD,IRS,SWLEG,2222222,2222222,2024-10-15
4,SCF,SCF,SCF,3815982,3672136,2020-02-02
5,IRD,LN_BR,SWLEG,14596583,13774383,2020-12-29
6,IRD,IRS,SWLEG,18343978,17356077,2024-10-15
7,IRD,LN_BR,SWLEG,19203839,18176215,2022-10-06
8,IRD,CF,SWLEG,20513130,19433281,2021-07-06
9,IRD,CF,SWLEG,20533916,19453781,2023-07-06
10,IRD,IRS,NaN,21183317,20077630,2040-07-13
11,IRD,IRS,FXD,33333333,33333333,2024-10-15
12,IRD,IRS,NaN,111222333,111222333,2024-10-15
13,IRD,IRS,NaN,222333111,222333111,2020-12-30
14,IRD,IRS,SCF,333111222,333111222,2020-12-12
15,IRD,IRS,NaN,444111222,444111222,2020-12-29
16,IRD,IRS,NaN,555111222,555111222,2024-10-15
17,IRD,IRS,NaN,564367838,564367838,2024-10-15
18,IRD,IRS,NaN,556111214,556111214,2021-07-06
19,EQD,EQUIT,FWD,10000001,10000001,2019-07-02
20,IRD,BOND,FWD,10000009,10000009,2021-06-12
22,CURR,FXD,SWLEG,19665186,18622136,2020-12-30
23,CURR,FXD,SWLEG,19772399,18724280,2020-12-30
24,CURR,FXD,SWLEG,19772400,18724280,2021-11-05
25,CURR,FXD,SWLEG,20980932,19883451,2021-05-04
26,CURR,FXD,SWLEG,20980933,19883451,2021-05-04
27,CURR,FXD,SWLEG,22798004,21622649,2024-10-15
30,CURR,FXD,SWLEG,20665178,19622128,2020-12-30
31,IRD,IRS,NaN,333244333,333244333,2024-10-15
32,IRD,IRS,NaN,35662435,35662435,2024-10-15
33,IRD,IRS,NaN,3323455,3323455,2020-12-30
34,IRD,IRS,NaN,67746567,67746567,2020-12-12
35,IRD,IRS,NaN,84564656,84564656,2021-05-04

In [10]:
#7.-Filtrado con trade_details a *null* en maturity para hacer la asignación en el DataFrame creado con la fusión de ambos archivos
# filtroNan = read_trade_details[read_trade_details.maturity.isnull()]
# filtroNan

#----AQUI ES DONDE ME SURGIA VARIAS DUDAS DE HACER JOIN CON LOS DATOS Y ASIGNARLOS DE UN DATAFRAME
# LOS VALORES QUE SE QUEDARIAN ASIGNADOS EN EL DATAFRAME FINAL ----